spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCLlXiMaMLTaA4smyKv1YXGGEaIrq+bbQitP27vQFtxHded8HxYmprjraOgT5DGDzUNeELd4aVnNU+Z+aTp00GRjVun/Rx8rpAUNrhcLvx3xcgSViCharaP9xJ9880Wk3MTRkwC+eszx3y/mLpqlvBEZ0VmxQmynPf1MgwidRzwu+RaUpFQb2RLQnKVWUQIdmci/jrE6dnMmHKoqJ/Y2mB2z2kIHNaMscQS265N7Z9sma9OgANXGoH5zLbFxHhq3UVXpl2Sbk5O9x1xbN3Iocm7z3noO891n4idxBB9FBI3YMMitkq67gAOPlJ7ffvFOkkwAkGM4k2gM6IeNhbuFQfw3Us31LtRu9eJwE2o+NAov/YHifaFALAHSiwYg5cwjOM='

token:
  expiration_time: 86400000
  secret: leganza

gateway:
  ip: 192.168.219.153  