spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCLlXiMaMLTaA4smyKv1YXGGEaIrq+bbQitP27vQFtxHded8HxYmprjraOgT5DGDzUNeELd4aVnNU+Z+aTp00GRjVun/Rx8rpAUNrhcLvx3xcgSViCharaP9xJ9880Wk3MTRkwC+eszx3y/mLpqlvBEZ0VmxQmynPf1MgwidRzwu+RaUpFQb2RLQnKVWUQIdmci/jrE6dnMmHKoqJ/Y2mB2z2kIHNaMscQS265N7Z9sma9OgANXGoH5zLbFxHhq3UVXpl2Sbk5O9x1xbN3Iocm7z3noO891n4idxBB9FBI3YMMitkq67gAOPlJ7ffvFOkkwAkGM4k2gM6IeNhbuFQfw3Us31LtRu9eJwE2o+NAov/YHifaFALAHSiwYg5cwjOM='

token:
  expiration_time: 86400000
  secret: '{cipher}AQBtG5h8SAmxJ+utFhOmKrV+oQgxK+pdFNQnx4vVZmGLdYCyeqpvxVy2osz6zuIaVZGHPlPju6aHTcaTZo/gJNfp3bd0VsgDY3ZaiXr6bu6WpuTpjvLM9FGi0WMcrOzxsuXfz4IzQXvNDmprCytTFLzk+dfLbI0DLxQbIfu7Rmh1X+FrcOjkNGUkrW8v4KXXm8X4MJSVyAr9uKATxokBkrkBM8aWCy73Gy67DE1Fdk0WARFgeQMaQSN0nAUzFCK9Kcx8c5Xka7LdGNxSP9L19X7cEcQxI8SnNGS95TANsTA1QfRBaVO2jUqkYfk3fZ18sHPjfRnl3cdXVrQRk1O26RrrmNyEuXif2G4N2foHQjkjNmvMsmKrmGL3rF9cxXVrlWI='

gateway:
  ip: 172.18.0.7

order-service:
  # url: http://127.0.0.1:8000/order-service/%s/orders    
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User's order is empty.    